services:
  load_balancer:
    build:
      context: ./load_balancer/app
      dockerfile: Dockerfile
    command: python aio_lb.py
    environment:
      HOST: localhost
      PORTS: "5001,5002,5003"
    ports:
      - "8001:8001"

  http:
    build:
      context: ./http_server/app
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    environment:
      - PORT=5000
    expose:
      - "5000"
    ports:
      - "5001-5003:5000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8040:80"
    depends_on:
      - load_balancer